// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2akVaS06f9qW1lceqfTaGT8eXGK2XKw4',
    appId: '1:848011551769:web:f905199bd71434d4753688',
    messagingSenderId: '848011551769',
    projectId: 'flash-chat-edc01',
    authDomain: 'flash-chat-edc01.firebaseapp.com',
    storageBucket: 'flash-chat-edc01.appspot.com',
    measurementId: 'G-FPVXRVL9B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoLZLK6kstIp0o5CVTgacYDZo56OVULc0',
    appId: '1:848011551769:android:7cf74491ec7e8583753688',
    messagingSenderId: '848011551769',
    projectId: 'flash-chat-edc01',
    storageBucket: 'flash-chat-edc01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfXDFtAbyl0GLrhRe2_DSssoG_9WN-fXI',
    appId: '1:848011551769:ios:e5ea60db67687a29753688',
    messagingSenderId: '848011551769',
    projectId: 'flash-chat-edc01',
    storageBucket: 'flash-chat-edc01.appspot.com',
    iosBundleId: 'com.example.flashchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfXDFtAbyl0GLrhRe2_DSssoG_9WN-fXI',
    appId: '1:848011551769:ios:49113eb328eb8907753688',
    messagingSenderId: '848011551769',
    projectId: 'flash-chat-edc01',
    storageBucket: 'flash-chat-edc01.appspot.com',
    iosBundleId: 'com.example.flashchat.RunnerTests',
  );
}
